# Format: "Local/RemoteTunnel user  host  ssh_port  local_port  remote_port"
TUNNELS=(
  # Tunnel 1 - Server x App y
  "L"	"user1"	"123.123.123.123"	"22"	"10001"	"2226"
  # Tunnel 2 - server y App Dozzle 
  "L"	"user2"	"124.124.124.124"	"22"	"10002"	"9999"
  # adminer - Server x 
  "L"	"user3"	"125.125.125.125"	"22"	"10003"	"8081"
)
